apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: course-db-secret-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/edutrack-cc-ass-2/secrets/course-db-password/versions/latest"
        fileName: "db_password"
