apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
  labels:
    app: enrollment-service
spec:
  selector:
    app: enrollment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Internal service, accessible only within the GKE cluster
