apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: student-db-secret-provider
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/edutrack-cc-ass-2/secrets/student-db-password/versions/latest"
        fileName: "db_password"
